In [1]:
import pandas as pd

## Test Normal Box Scores

In [4]:
box_scores = pd.read_csv("Basketball/Box_Scores.csv", compression='gzip', encoding='latin1')

In [7]:
box_scores.head()

,Game_id,Person_id,Team_id,First_Name,Last_Name,minutes,Field_Goals,Field_Goals_Attempted,Field_Goal_Percentage,Three_Pointers,...,Fast_Break_Points,Triple_Doubles,Double_Doubles,actual_minutes,actual_seconds,Plus_Minus,Blocks_Against,PTS_OFF_TO,Second_Chance_PTS,Total_Rebounds
0,20300001,224,1610612748,Eddie,Jones,39,5,15,0.333,1,...,0.0,0.0,0.0,39,0,-7,0.0,2,2,8.0
1,20300001,243,1610612755,Aaron,McKie,24,3,7,0.429,2,...,2.0,0.0,0.0,24,0,15,0.0,5,3,4.0
2,20300001,258,1610612748,Brian,Grant,29,4,5,0.800,0,...,0.0,0.0,0.0,29,0,-11,1.0,0,4,7.0
3,20300001,727,1610612755,Eric,Snow,31,0,5,0.000,0,...,1.0,0.0,0.0,31,0,11,1.0,1,0,4.0
4,20300001,902,1610612748,Vernell,Coles,5,0,0,0.000,0,...,0.0,0.0,0.0,5,0,-4,0.0,0,0,0.0

## Test Tracking Data Events

In [10]:
events_test = pd.read_json("Basketball/Player_Tracking/CLEBOS/2017051902_nba-bos_EVENTS.jsonl", lines=True)

In [12]:
events_test.head()

,awayPlayers,eventType,gameClock,gameId,homePlayers,pbpId,period,playerId,shotClock,wallClock
0,"[ff41f1fa-89ef-11e6-a048-a45e60e298d3, ff403f7...",TOUCH,719.11,41a49717-2318-4ea4-ac6a-aeebafcbdf0c,"[ff415a3a-89ef-11e6-a0bf-a45e60e298d3, ff413f4...",NaN,1,ff413f45-89ef-11e6-94c9-a45e60e298d3,23.1,1495240347417
1,"[ff41f1fa-89ef-11e6-a048-a45e60e298d3, ff403f7...",DRIBBLE,717.99,41a49717-2318-4ea4-ac6a-aeebafcbdf0c,"[ff415a3a-89ef-11e6-a0bf-a45e60e298d3, ff413f4...",NaN,1,ff413f45-89ef-11e6-94c9-a45e60e298d3,22.0,1495240348536
2,"[ff41f1fa-89ef-11e6-a048-a45e60e298d3, ff403f7...",DRIBBLE,717.31,41a49717-2318-4ea4-ac6a-aeebafcbdf0c,"[ff415a3a-89ef-11e6-a0bf-a45e60e298d3, ff413f4...",NaN,1,ff413f45-89ef-11e6-94c9-a45e60e298d3,21.3,1495240349216
3,"[ff41f1fa-89ef-11e6-a048-a45e60e298d3, ff403f7...",DRIBBLE,716.50,41a49717-2318-4ea4-ac6a-aeebafcbdf0c,"[ff415a3a-89ef-11e6-a0bf-a45e60e298d3, ff413f4...",NaN,1,ff413f45-89ef-11e6-94c9-a45e60e298d3,20.5,1495240350016
4,"[ff41f1fa-89ef-11e6-a048-a45e60e298d3, ff403f7...",DRIBBLE,713.42,41a49717-2318-4ea4-ac6a-aeebafcbdf0c,"[ff415a3a-89ef-11e6-a0bf-a45e60e298d3, ff413f4...",NaN,1,ff413f45-89ef-11e6-94c9-a45e60e298d3,17.4,1495240353096

## Test Tracking Data Raw

In [17]:
tracking_test = pd.read_json("Basketball/Player_Tracking/CLEBOS/2017051902_nba-bos_TRACKING.jsonl.gz", lines=True,
                             compression='gzip', encoding='latin1')

In [30]:
tracking_test.head()

,awayPlayers,ball,frameIdx,gameClock,gameClockStopped,homePlayers,period,shotClock,wallClock
0,[{'playerId': 'ff41e9f0-89ef-11e6-87b7-a45e60e...,"{'xyz': [1.56, 8.88, 3.52]}",0,720.0,True,[{'playerId': 'ff427c2e-89ef-11e6-8d2a-a45e60e...,1,24.0,1495240341536
1,[{'playerId': 'ff41e9f0-89ef-11e6-87b7-a45e60e...,"{'xyz': [0.64, 8.06, 4.49]}",1,720.0,True,[{'playerId': 'ff427c2e-89ef-11e6-8d2a-a45e60e...,1,24.0,1495240341576
2,[{'playerId': 'ff41e9f0-89ef-11e6-87b7-a45e60e...,"{'xyz': [0.59, 8.22, 4.28]}",2,720.0,True,[{'playerId': 'ff427c2e-89ef-11e6-8d2a-a45e60e...,1,24.0,1495240341616
3,[{'playerId': 'ff41e9f0-89ef-11e6-87b7-a45e60e...,"{'xyz': [1.25, 8.72, 3.77]}",3,720.0,True,[{'playerId': 'ff427c2e-89ef-11e6-8d2a-a45e60e...,1,24.0,1495240341656
4,[{'playerId': 'ff41e9f0-89ef-11e6-87b7-a45e60e...,"{'xyz': [1.4, 8.69, 3.79]}",4,720.0,True,[{'playerId': 'ff427c2e-89ef-11e6-8d2a-a45e60e...,1,24.0,1495240341696

In [31]:
tracking_test.iloc[0,:]['awayPlayers']

[{'playerId': 'ff41e9f0-89ef-11e6-87b7-a45e60e298d3',
  'xyz': [-24.66, -5.57, 0.0]},
 {'playerId': 'ff403f7d-89ef-11e6-b44d-a45e60e298d3',
  'xyz': [1.47, 11.13, 0.0]},
 {'playerId': 'ff42aecf-89ef-11e6-8cb8-a45e60e298d3',
  'xyz': [-10.35, 1.3599999999999999, 0.0]},
 {'playerId': 'ff4221b5-89ef-11e6-b799-a45e60e298d3',
  'xyz': [-25.3, 1.9500000000000002, 0.0]},
 {'playerId': 'ff41f1fa-89ef-11e6-a048-a45e60e298d3',
  'xyz': [-1.15, -0.37, 0.0]}]

## Test Tracking Data Box Score

In [32]:
import json

In [41]:
data = {}
with open("Basketball/Player_Tracking/CLEBOS/2017051902_nba-bos_BOX.json", "r") as read_file:
    data = json.load(read_file)

In [93]:
keys = list(data.keys())

In [76]:
summarized_data = {k: None for k in keys}
summarized_data

{'game-state': None,
 'contested_shots_agg': None,
 'defensive_shots_agg': None,
 'drives_agg': None,
 'isolations_agg': None,
 'matchups_agg': None,
 'passes_agg': None,
 'passes_pairings_agg': None,
 'posts_agg': None,
 'rebounds_agg': None,
 'shots_agg': None,
 'speed_loads_agg': None,
 'touches_agg': None}

In [92]:
for key in keys:
    if key == 'game-state':
        summarized_data[key] = pd.DataFrame(data[key], index=[0])
    else:
        summarized_data[key] = pd.DataFrame(data[key], index=[i for i in range(len(data[key]))])

In [91]:
summarized_data['game-state']

,game_status,game_clock,period_status,period,game_id,home_score,away_score
0,3,,final,4,41a49717-2318-4ea4-ac6a-aeebafcbdf0c,86,130